using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;

namespace AutoTranslateTexts
{
    public class Program
    {
        public static Lazy<Settings> _settings = null!;
        public static Settings settings => _settings.Value;

        private static readonly IReadOnlyList<IPatcherModule> Modules = new IPatcherModule[]
        {
            new BookModule(),
            new LocationModule(),
            new NameModule(),
            new ItemModule(),
            new DialogueModule()
        };

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out _settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "Auto Translate Texts.esp")
                .Run(args);
        }

        private static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            Console.OutputEncoding = Encoding.UTF8;

            foreach (var module in Modules)
            {
                var moduleSettings = module.GetSettings(settings);
                if (!moduleSettings.Enabled)
                {
                    continue;
                }

                module.Run(state, settings.TargetLanguage, moduleSettings.Log);
            }
        }
    }
}
