using System;
using System.Text;
using System.Threading.Tasks;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using Noggog;
using System.Collections.Generic;
using Mutagen.Bethesda.Plugins;

namespace AutoTranslateTexts
{
    public class Program
    {
        public static Lazy<Settings> _settings = null!;
        public static Settings settings => _settings.Value;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out _settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "Auto Translate Texts.esp")
                .Run(args);
        }

        private static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            Console.OutputEncoding = Encoding.UTF8;

            if (settings.Books)
            {
                BookPatcher.Run(state, settings.BookLog);
            }

            if (settings.Locations)
            {
                LocationPatcher.Run(state, settings.LocationsLog);
            }

            if (settings.Names)
            {
                NamePatcher.Run(state, settings.NamesLog);
            }

            if (settings.Items)
            {
                ItemPatcher.Run(state, settings.ItemsLog);
            }
        }
    }
}